INSERT INTO PRODUCT(NAME, PRICE, VAT_AMOUNT, VAT_INCLUSIVE_PRICE, FK_CATEGORY_ID)
VALUES ('Pizza', 1, 1, 1, 1);
INSERT INTO PRODUCT(NAME, PRICE, VAT_AMOUNT, VAT_INCLUSIVE_PRICE, FK_CATEGORY_ID)
VALUES ('Burger', 1, 1, 1, 1);