INSERT INTO CATEGORY(NAME, VAT_RATE)
VALUES ('Food', 0.01);
INSERT INTO CATEGORY(NAME, VAT_RATE)
VALUES ('Stationery', 0.08);
INSERT INTO CATEGORY(NAME, VAT_RATE)
VALUES ('Clothes', 0.08);
INSERT INTO CATEGORY(NAME, VAT_RATE)
VALUES ('Technology', 0.18);
INSERT INTO CATEGORY(NAME, VAT_RATE)
VALUES ('Cleaning', 0.18);
INSERT INTO CATEGORY(NAME, VAT_RATE)
VALUES ('Other', 0.18);